/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SavingPlannerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getAchievability"
      | "getCurrentSaving"
      | "getRate"
      | "getRequiredSaving"
      | "getTarget"
      | "getTime"
      | "recalculateSavingsPlan"
      | "recalculateSavingsPlanWithParams"
      | "submitSavingsPlan"
      | "userSavingsData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAchievability",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentSaving",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredSaving",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTarget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recalculateSavingsPlan",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recalculateSavingsPlanWithParams",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSavingsPlan",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "userSavingsData",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAchievability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentSaving",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredSaving",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTarget", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recalculateSavingsPlan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recalculateSavingsPlanWithParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSavingsPlan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userSavingsData",
    data: BytesLike
  ): Result;
}

export interface SavingPlanner extends BaseContract {
  connect(runner?: ContractRunner | null): SavingPlanner;
  waitForDeployment(): Promise<this>;

  interface: SavingPlannerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getAchievability: TypedContractMethod<
    [userAddress: AddressLike],
    [string],
    "view"
  >;

  getCurrentSaving: TypedContractMethod<
    [userAddress: AddressLike],
    [string],
    "view"
  >;

  getRate: TypedContractMethod<[userAddress: AddressLike], [string], "view">;

  getRequiredSaving: TypedContractMethod<
    [userAddress: AddressLike],
    [string],
    "view"
  >;

  getTarget: TypedContractMethod<[userAddress: AddressLike], [string], "view">;

  getTime: TypedContractMethod<[userAddress: AddressLike], [string], "view">;

  recalculateSavingsPlan: TypedContractMethod<[], [void], "nonpayable">;

  recalculateSavingsPlanWithParams: TypedContractMethod<
    [annualRateScaled6: BigNumberish, months: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitSavingsPlan: TypedContractMethod<
    [
      encryptedTarget: BytesLike,
      encryptedRate: BytesLike,
      encryptedTime: BytesLike,
      encryptedCurrentSaving: BytesLike,
      inputProof: BytesLike,
      annualRateScaled6: BigNumberish,
      months: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  userSavingsData: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, string, string] & {
        target: string;
        rate: string;
        time: string;
        currentSaving: string;
        requiredSaving: string;
        achievability: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAchievability"
  ): TypedContractMethod<[userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentSaving"
  ): TypedContractMethod<[userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRate"
  ): TypedContractMethod<[userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRequiredSaving"
  ): TypedContractMethod<[userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTarget"
  ): TypedContractMethod<[userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTime"
  ): TypedContractMethod<[userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "recalculateSavingsPlan"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recalculateSavingsPlanWithParams"
  ): TypedContractMethod<
    [annualRateScaled6: BigNumberish, months: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitSavingsPlan"
  ): TypedContractMethod<
    [
      encryptedTarget: BytesLike,
      encryptedRate: BytesLike,
      encryptedTime: BytesLike,
      encryptedCurrentSaving: BytesLike,
      inputProof: BytesLike,
      annualRateScaled6: BigNumberish,
      months: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userSavingsData"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, string, string] & {
        target: string;
        rate: string;
        time: string;
        currentSaving: string;
        requiredSaving: string;
        achievability: string;
      }
    ],
    "view"
  >;

  filters: {};
}
